import { Context ,Next } from 'koa'

const FAILCODE = -1
const PASSWORDSALT = 'FGYH459T7Y45HG5FYG34GR&$()?'
const SETSESSIONTOKENSALT = 'AF98RF8T34U3UG34598389'
const ERRORTIPS = '系统错误，请联系帅气的管理员'
const ACCESS_TOKEN_EXPIRE_Time = 60 * 2

export {
    FAILCODE,
    PASSWORDSALT,
    SETSESSIONTOKENSALT,
    ERRORTIPS,
    ACCESS_TOKEN_EXPIRE_Time
}